### ISSUE TITLE
Migrate to standardised workflows

### ISSUE THREAD

**Issue by cyri113** [TogetherCrew/discord-bot#59]
**start.staging.yml**
```yml
name: Staging CI/CD Pipeline

on: pull_request

jobs:
  ci:
    uses: TogetherCrew/operations/.github/workflows/ci.yml@main
    secrets:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
```

**production.yml**
```yml
name: Production CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    uses: TogetherCrew/operations/.github/workflows/ci.yml@main
    secrets:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
```

This will require some refactoring for the coding standards.
